### ISSUE TITLE
Q: README.md 

### ISSUE THREAD

**Issue by erayarslan** [reconquest/shadowd#5]
any config, theme? for [this](https://camo.githubusercontent.com/2e71a2c67dcbe08f5065b04fb5ee06037aeda52f/687474703a2f2f692e696d6775722e636f6d2f66624b59544d582e676966)

and can u share with me : )

**Comment by seletskiy** [comment]
@erayarslan:

Xresources theme: https://github.com/seletskiy/dotfiles/blob/master/.Xresources.dark
Prompt theme (ZSH): https://github.com/seletskiy/zsh-prompt-lambda17
Font: https://github.com/seletskiy/monaco-font

Yes, I'm insane, I did it by myself.

**Comment by erayarslan** [comment]
Archived! Thanks mate 👍
